sudo: required
services:
  - docker

before_install:
  - docker build -t coen163/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true coen163/react-test npm test

after_success:
  - docker build -t coen163/multi-client ./client
  - docker build -t coen163/multi-nginx ./nginx
  - docker build -t coen163/multi-server ./server
  - docker build -t coen163/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push coen163/multi-client
  - docker push coen163/multi-nginx
  - docker push coen163/multi-server
  - docker push coen163/multi-worker